export const SET_DEFAULT_LOCATION = "SET_DEFAULT_LOCATION";
export const FETCH_LOCATION = "FETCH_LOCATION";
export const FETCH_LOCATION_PENDING = "FETCH_LOCATION_PENDING";
export const FETCH_LOCATION_FULFILLED = "FETCH_LOCATION_FULFILLED";
export const FETCH_LOCATION_REJECTED = "FETCH_LOCATION_REJECTED";

export const FETCH_EVENTS_LIST = "FETCH_EVENTS_LIST";
export const FETCH_EVENTS_LIST_PENDING = "FETCH_EVENTS_LIST_PENDING";
export const FETCH_EVENTS_LIST_FUFILLED = "FETCH_EVENTS_LIST_FULFILLED";
export const FETCH_EVENTS_LIST_REJECTED = "FETCH_EVENTS_LIST_REJECTED";

export const CREATE_EVENT = "CREATE_EVENT";
export const FORM_DATA_CHANGED = "FORM_DATA_CHANGED";
export const CLEAR_FORM = "CLEAR_FORM";

export const EXPAND_CARD = "EXPAND_CARD";
export const HIDE_CARD = "HIDE_CARD";
export const LOAD_CARD_DATA = "LOAD_CARD_DATA";
